"""Built-in, non-sensitive starting points for local Automation Center profiles."""

from typing import Any, Dict, List


BUILTIN_PROFILE_TEMPLATES: List[Dict[str, Any]] = [
    {
        "id": "business-management",
        "name": "Business & Management",
        "description": "Strategic management, operations and business development starting point.",
        "icon": "briefcase",
        "data": {
            "profession": {"name": "Business professional", "sector": "Business", "level": ""},
            "interests": [{"name": "Strategy", "weight": 8}, {"name": "Operations", "weight": 7}, {"name": "Leadership", "weight": 7}],
            "skills": ["Business analysis", "Project management"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["Business strategy", "Management", "Markets"],
            "excluded_topics": [],
            "goals": ["Follow industry news", "Build professional network"],
            "preferences": {"news_frequency": "daily", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "law",
        "name": "Derecho",
        "description": "Legal practice, regulation and jurisprudence starting point.",
        "icon": "scale",
        "data": {
            "profession": {"name": "Legal professional", "sector": "Legal", "level": ""},
            "interests": [{"name": "Legislation", "weight": 10}, {"name": "Jurisprudence", "weight": 9}, {"name": "European law", "weight": 8}],
            "skills": ["Legal research", "Legal writing"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish"],
            "topics": ["Legislation", "Jurisprudence", "Regulation"],
            "excluded_topics": [],
            "goals": ["Follow industry news", "Research"],
            "preferences": {"news_frequency": "daily", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "economics-finance",
        "name": "Economía & Finanzas",
        "description": "Economics, financial markets and policy starting point.",
        "icon": "chart",
        "data": {
            "profession": {"name": "Economics and finance professional", "sector": "Finance", "level": ""},
            "interests": [{"name": "Macroeconomics", "weight": 9}, {"name": "Financial markets", "weight": 9}, {"name": "Central banking", "weight": 8}],
            "skills": ["Financial analysis", "Data analysis"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["Inflation", "Interest rates", "Markets"],
            "excluded_topics": [],
            "goals": ["Follow industry news", "Research"],
            "preferences": {"news_frequency": "daily", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "technology",
        "name": "Tecnología",
        "description": "Software, artificial intelligence and digital products starting point.",
        "icon": "code",
        "data": {
            "profession": {"name": "Technology professional", "sector": "Technology", "level": ""},
            "interests": [{"name": "Artificial intelligence", "weight": 10}, {"name": "Software engineering", "weight": 9}, {"name": "Cybersecurity", "weight": 7}],
            "skills": ["Programming", "Systems design"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["AI", "Software", "Cloud computing"],
            "excluded_topics": [],
            "goals": ["Follow industry news", "Find jobs", "Training"],
            "preferences": {"news_frequency": "daily", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "engineering",
        "name": "Ingeniería",
        "description": "General engineering, systems and innovation starting point.",
        "icon": "tools",
        "data": {
            "profession": {"name": "Engineer", "sector": "Engineering", "level": ""},
            "interests": [{"name": "Systems engineering", "weight": 9}, {"name": "Innovation", "weight": 8}, {"name": "Manufacturing", "weight": 7}],
            "skills": ["Problem solving", "Technical analysis"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["Engineering", "Innovation", "Industry"],
            "excluded_topics": [],
            "goals": ["Follow industry news", "Find jobs", "Training"],
            "preferences": {"news_frequency": "daily", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "aerospace-engineering",
        "name": "Ingeniería Aeroespacial",
        "description": "Aviation, space and satellite systems starting point.",
        "icon": "rocket",
        "data": {
            "profession": {"name": "Aerospace engineer", "sector": "Aerospace", "level": ""},
            "interests": [{"name": "Aviation", "weight": 10}, {"name": "Space", "weight": 10}, {"name": "Satellites", "weight": 8}],
            "skills": ["Aerodynamics", "Aircraft design", "Python"],
            "companies": ["Airbus", "ESA", "NASA"],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["Aviation", "Space", "Defense"],
            "excluded_topics": [],
            "goals": ["Find jobs", "Follow industry news", "Build personal brand"],
            "preferences": {"news_frequency": "daily", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "medicine",
        "name": "Medicina",
        "description": "Clinical practice, research and healthcare starting point.",
        "icon": "health",
        "data": {
            "profession": {"name": "Healthcare professional", "sector": "Healthcare", "level": ""},
            "interests": [{"name": "Clinical research", "weight": 9}, {"name": "Public health", "weight": 8}, {"name": "Medical innovation", "weight": 8}],
            "skills": ["Evidence review", "Clinical communication"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["Healthcare", "Research", "Medical policy"],
            "excluded_topics": [],
            "goals": ["Follow industry news", "Research", "Training"],
            "preferences": {"news_frequency": "daily", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "science",
        "name": "Ciencia",
        "description": "Scientific research, methods and publications starting point.",
        "icon": "flask",
        "data": {
            "profession": {"name": "Scientist", "sector": "Science", "level": ""},
            "interests": [{"name": "Research", "weight": 10}, {"name": "Scientific publications", "weight": 9}, {"name": "Innovation", "weight": 7}],
            "skills": ["Scientific writing", "Data analysis"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["Research", "Science policy", "Publications"],
            "excluded_topics": [],
            "goals": ["Research", "Follow industry news", "Training"],
            "preferences": {"news_frequency": "weekly", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "marketing",
        "name": "Marketing",
        "description": "Marketing strategy, audiences and brand building starting point.",
        "icon": "megaphone",
        "data": {
            "profession": {"name": "Marketing professional", "sector": "Marketing", "level": ""},
            "interests": [{"name": "Digital marketing", "weight": 9}, {"name": "Brand strategy", "weight": 9}, {"name": "Content", "weight": 8}],
            "skills": ["Content strategy", "Audience research"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["Marketing", "Branding", "Social media"],
            "excluded_topics": [],
            "goals": ["Build personal brand", "Follow industry news"],
            "preferences": {"news_frequency": "daily", "relevance_level": "medium", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "architecture",
        "name": "Arquitectura",
        "description": "Architecture, urbanism and construction starting point.",
        "icon": "building",
        "data": {
            "profession": {"name": "Architect", "sector": "Architecture", "level": ""},
            "interests": [{"name": "Sustainable design", "weight": 9}, {"name": "Urbanism", "weight": 8}, {"name": "Construction", "weight": 8}],
            "skills": ["Design", "Project coordination"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["Architecture", "Urbanism", "Sustainability"],
            "excluded_topics": [],
            "goals": ["Follow industry news", "Find jobs", "Build personal brand"],
            "preferences": {"news_frequency": "weekly", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "education",
        "name": "Educación",
        "description": "Teaching, learning design and education policy starting point.",
        "icon": "academic",
        "data": {
            "profession": {"name": "Education professional", "sector": "Education", "level": ""},
            "interests": [{"name": "Learning design", "weight": 9}, {"name": "Education technology", "weight": 8}, {"name": "Education policy", "weight": 7}],
            "skills": ["Teaching", "Curriculum design"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["Education", "EdTech", "Learning"],
            "excluded_topics": [],
            "goals": ["Training", "Follow industry news"],
            "preferences": {"news_frequency": "weekly", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "journalism",
        "name": "Periodismo",
        "description": "Journalism, media and current affairs starting point.",
        "icon": "news",
        "data": {
            "profession": {"name": "Journalist", "sector": "Media", "level": ""},
            "interests": [{"name": "Current affairs", "weight": 10}, {"name": "Investigative reporting", "weight": 8}, {"name": "Media innovation", "weight": 7}],
            "skills": ["Research", "Writing"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["News", "Media", "Public policy"],
            "excluded_topics": [],
            "goals": ["Follow industry news", "Research", "Build personal brand"],
            "preferences": {"news_frequency": "daily", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "student",
        "name": "Estudiante",
        "description": "Learning, career preparation and academic research starting point.",
        "icon": "graduation",
        "data": {
            "profession": {"name": "Student", "sector": "", "level": "Student"},
            "interests": [{"name": "Learning", "weight": 10}, {"name": "Career development", "weight": 9}, {"name": "Research", "weight": 8}],
            "skills": [],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["Education", "Career", "Scholarships"],
            "excluded_topics": [],
            "goals": ["Training", "Find jobs", "Research"],
            "preferences": {"news_frequency": "weekly", "relevance_level": "medium", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
    {
        "id": "entrepreneur",
        "name": "Emprendedor",
        "description": "Entrepreneurship, product validation and growth starting point.",
        "icon": "lightbulb",
        "data": {
            "profession": {"name": "Entrepreneur", "sector": "Business", "level": ""},
            "interests": [{"name": "Startups", "weight": 10}, {"name": "Product strategy", "weight": 9}, {"name": "Fundraising", "weight": 8}],
            "skills": ["Product management", "Business development"],
            "companies": [],
            "locations": [],
            "languages": ["Spanish", "English"],
            "topics": ["Startups", "Venture capital", "Innovation"],
            "excluded_topics": [],
            "goals": ["Build personal brand", "Follow industry news", "Automate email"],
            "preferences": {"news_frequency": "daily", "relevance_level": "high", "sources": [], "notifications_enabled": True, "additional_settings": {}},
            "automations": [],
        },
    },
]
